# Generated by Django 3.2 on 2021-12-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20211223_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount',
            new_name='amount',
        ),
    ]
