# Generated by Django 3.2.6 on 2021-09-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_auto_20210917_1706"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="orginal_bag",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_pid",
            field=models.CharField(default="", max_length=254),
        ),
    ]
